### HTTP request
GET http://nexcore.net/test.html
Connection: keep-alive
Proxy-Authorization: Basic asds
Accept-Encoding: 


### Invalid HTTPS Request
GET https://nexcore.net/test.html
Connection: keep-alive
Proxy-Authorization: Basic asds
Accept-Encoding: 


### Echo
POST http://api.mready.net/echo
Connection: keep-alive
Proxy-Authorization: Basic asds

hello


### Direct to proxy
GET http://localhost:8088/


### HTTPS Request (with redirect)
GET https://google.com/
Connection: keep-alive


### HTTPS Request
GET https://api.github.com 
Connection: keep-alive


### HTTP reverse proxy
GET http://localhost:8088/r/nexcore.net/test.html


### HTTPS reverse proxy
GET http://localhost:8088/r/google.com:443/
