GET http://nexcore.net/test.html
Connection: keep-alive
Proxy-Authorization: Basic asds
Accept-Encoding: 

###

GET https://nexcore.net/test.html
Connection: keep-alive
Proxy-Authorization: Basic asds
Accept-Encoding: 

###

POST http://api.mready.net/echo
Connection: keep-alive
Proxy-Authorization: Basic asds

hello

###

GET http://localhost:8088/


###

GET https://google.com/
Connection: keep-alive

###

GET https://api.github.com 
Connection: keep-alive